export enum PremumActionTypes {
  CREATE_PREMIUM = "CREATE_PREMIUM",
  LOAD_PREMIUM_SUCCESS = "LOAD_PREMIUM_SUCCESS",
  CREATE_PREMIUM_SUCCESS = "CREATE_PREMIUM_SUCCESS",
  UPDATE_PREMIUM_SUCCESS = "UPDATE_PREMIUM_SUCCESS",
  DELETE_PREMIUM_OPTIMISTIC = "DELETE_PREMIUM",
}
